// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Ur-E3n3FMsG-j2FAKYsPNTi4m07v11g',
    appId: '1:641635707875:web:57b3803fe20dc76dbe4ed6',
    messagingSenderId: '641635707875',
    projectId: 'chatapp-2370e',
    authDomain: 'chatapp-2370e.firebaseapp.com',
    storageBucket: 'chatapp-2370e.appspot.com',
    measurementId: 'G-3LB2HRXXKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjARNFErq4XQUKD7RDyOy6_0TrgYm7SM',
    appId: '1:641635707875:android:7a9727e68773103bbe4ed6',
    messagingSenderId: '641635707875',
    projectId: 'chatapp-2370e',
    storageBucket: 'chatapp-2370e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdxE94jE3kfQV9G7OJw2JvfGuMYAlV2M',
    appId: '1:641635707875:ios:15892b302a2ab7fdbe4ed6',
    messagingSenderId: '641635707875',
    projectId: 'chatapp-2370e',
    storageBucket: 'chatapp-2370e.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdxE94jE3kfQV9G7OJw2JvfGuMYAlV2M',
    appId: '1:641635707875:ios:15892b302a2ab7fdbe4ed6',
    messagingSenderId: '641635707875',
    projectId: 'chatapp-2370e',
    storageBucket: 'chatapp-2370e.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Ur-E3n3FMsG-j2FAKYsPNTi4m07v11g',
    appId: '1:641635707875:web:db1a8966aeabaf15be4ed6',
    messagingSenderId: '641635707875',
    projectId: 'chatapp-2370e',
    authDomain: 'chatapp-2370e.firebaseapp.com',
    storageBucket: 'chatapp-2370e.appspot.com',
    measurementId: 'G-0M9PG0EYN9',
  );

}